###
GET http://localhost:3000/categories

###
GET http://localhost:3000/categories/9
Accept: application/json


###
DELETE http://localhost:3000/categories/8
Content-Type: application/json


###
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name":"ayoub"  }


###
PATCH  http://localhost:3000/categories/1
Content-Type: application/json

{
    "name":"hgdh"
  }