###
GET http://localhost:3000/users
Accept: application/json

###
GET http://localhost:3000/users/6
Accept: application/json

###
DELETE http://localhost:3000/users/12
Content-Type: application/json

###
POST http://localhost:3000/users
Content-Type: application/json

{

  "email": "yy@gmail.com",
    "name": "tht",
    "role": "USER"
  }


###
PATCH  http://localhost:3000/users/1
Content-Type: application/json

   {
    "email": "etoullnjali@gmail.com",
    "name": "etoulnblali",
    "role": "USER"
  }
  